"""Add worship schedule tables

Revision ID: 37c4643f69fd
Revises: add_daily_verses_001
Create Date: 2025-08-01 18:19:22.939357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37c4643f69fd"
down_revision: Union[str, None] = "add_daily_verses_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worship_service_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("church_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["church_id"],
            ["churches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worship_service_categories_id"),
        "worship_service_categories",
        ["id"],
        unique=False,
    )
    op.create_table(
        "worship_services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("church_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("service_type", sa.String(length=50), nullable=True),
        sa.Column("target_group", sa.String(length=50), nullable=True),
        sa.Column("is_online", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["church_id"],
            ["churches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worship_services_id"), "worship_services", ["id"], unique=False
    )
    op.drop_index("ix_daily_verses_is_active", table_name="daily_verses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_daily_verses_is_active", "daily_verses", ["is_active"], unique=False
    )
    op.drop_index(op.f("ix_worship_services_id"), table_name="worship_services")
    op.drop_table("worship_services")
    op.drop_index(
        op.f("ix_worship_service_categories_id"),
        table_name="worship_service_categories",
    )
    op.drop_table("worship_service_categories")
    # ### end Alembic commands ###
