"""Add push notification tables

Revision ID: 81f8e0f81892
Revises: 37c4643f69fd
Create Date: 2025-08-01 20:43:55.531811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f8e0f81892'
down_revision: Union[str, None] = '37c4643f69fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('ANNOUNCEMENT', 'WORSHIP_REMINDER', 'ATTENDANCE', 'BIRTHDAY', 'PRAYER_REQUEST', 'SYSTEM', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('data_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement', sa.Boolean(), nullable=True),
    sa.Column('worship_reminder', sa.Boolean(), nullable=True),
    sa.Column('attendance', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.Boolean(), nullable=True),
    sa.Column('prayer_request', sa.Boolean(), nullable=True),
    sa.Column('system', sa.Boolean(), nullable=True),
    sa.Column('do_not_disturb', sa.Boolean(), nullable=True),
    sa.Column('dnd_start_time', sa.String(length=5), nullable=True),
    sa.Column('dnd_end_time', sa.String(length=5), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ANNOUNCEMENT', 'WORSHIP_REMINDER', 'ATTENDANCE', 'BIRTHDAY', 'PRAYER_REQUEST', 'SYSTEM', 'CUSTOM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_users', sa.JSON(), nullable=True),
    sa.Column('target_groups', sa.JSON(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('delivered_count', sa.Integer(), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_notifications_id'), 'push_notifications', ['id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', 'WEB', name='deviceplatform'), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_token'), 'user_devices', ['device_token'], unique=True)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_table('notification_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'DELIVERED', 'READ', name='notificationstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['push_notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_recipients_id'), 'notification_recipients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_recipients_id'), table_name='notification_recipients')
    op.drop_table('notification_recipients')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_token'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_push_notifications_id'), table_name='push_notifications')
    op.drop_table('push_notifications')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###