"""Add encrypted_password to users table

Revision ID: 8491fbe48bcf
Revises: d95901f2714f
Create Date: 2025-07-31 14:03:56.790568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8491fbe48bcf'
down_revision: Union[str, None] = 'd95901f2714f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###