"""Add is_first column to users table

Revision ID: 95f1b7edcb31
Revises: 8491fbe48bcf
Create Date: 2025-07-31 19:35:37.133331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95f1b7edcb31"
down_revision: Union[str, None] = "8491fbe48bcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_first", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_first")
    # ### end Alembic commands ###
