"""Add community platform models - sharing, requests, jobs, music, events

Revision ID: community_platform_001
Revises: simple_login_history_001
Create Date: 2025-09-10 07:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'community_platform_001'
down_revision = 'simple_login_history_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create community_sharing table
    op.create_table('community_sharing',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('description', sa.Text(), nullable=False, comment='상세 설명'),
        sa.Column('category', sa.String(length=20), nullable=False, comment='카테고리'),
        sa.Column('condition', sa.String(length=50), nullable=True, comment='상태 (양호, 보통, 나쁨)'),
        sa.Column('images', sa.JSON(), nullable=True, comment='이미지 URL 배열'),
        sa.Column('location', sa.String(length=100), nullable=False, comment='지역'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('pickup_location', sa.String(length=200), nullable=True, comment='픽업 장소'),
        sa.Column('available_times', sa.Text(), nullable=True, comment='가능한 시간'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='상태'),
        sa.Column('recipient_info', sa.String(length=200), nullable=True, comment='수령자 정보'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='만료일시'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_sharing_id'), 'community_sharing', ['id'], unique=False)
    
    # Create community_requests table
    op.create_table('community_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('description', sa.Text(), nullable=False, comment='상세 설명'),
        sa.Column('category', sa.String(length=20), nullable=False, comment='카테고리'),
        sa.Column('urgency_level', sa.String(length=10), nullable=False, comment='긴급도'),
        sa.Column('needed_by', sa.DateTime(timezone=True), nullable=True, comment='필요한 날짜'),
        sa.Column('request_reason', sa.Text(), nullable=True, comment='요청 사유'),
        sa.Column('images', sa.JSON(), nullable=True, comment='참고 이미지 URL 배열'),
        sa.Column('location', sa.String(length=100), nullable=False, comment='지역'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='상태'),
        sa.Column('provider_info', sa.String(length=200), nullable=True, comment='제공자 정보'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_requests_id'), 'community_requests', ['id'], unique=False)
    
    # Create job_posts table
    op.create_table('job_posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('company', sa.String(length=100), nullable=False, comment='회사명'),
        sa.Column('position', sa.String(length=100), nullable=False, comment='직책/포지션'),
        sa.Column('employment_type', sa.String(length=20), nullable=False, comment='고용 형태'),
        sa.Column('location', sa.String(length=100), nullable=False, comment='근무 지역'),
        sa.Column('salary', sa.String(length=100), nullable=True, comment='급여'),
        sa.Column('work_hours', sa.String(length=100), nullable=True, comment='근무 시간'),
        sa.Column('description', sa.Text(), nullable=False, comment='상세 설명'),
        sa.Column('requirements', sa.Text(), nullable=True, comment='자격 요건'),
        sa.Column('benefits', sa.Text(), nullable=True, comment='복리후생'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='마감일'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='상태'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posts_id'), 'job_posts', ['id'], unique=False)
    
    # Create job_seekers table
    op.create_table('job_seekers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('desired_position', sa.String(length=100), nullable=False, comment='희망 직책'),
        sa.Column('employment_type', sa.String(length=20), nullable=False, comment='희망 고용 형태'),
        sa.Column('desired_location', sa.String(length=100), nullable=False, comment='희망 근무 지역'),
        sa.Column('desired_salary', sa.String(length=100), nullable=True, comment='희망 급여'),
        sa.Column('experience', sa.Text(), nullable=True, comment='경력'),
        sa.Column('skills', sa.Text(), nullable=True, comment='기술/스킬'),
        sa.Column('education', sa.String(length=100), nullable=True, comment='학력'),
        sa.Column('introduction', sa.Text(), nullable=False, comment='자기소개'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('available_from', sa.DateTime(timezone=True), nullable=True, comment='근무 가능 시작일'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='상태'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_seekers_id'), 'job_seekers', ['id'], unique=False)
    
    # Create music_team_recruits table
    op.create_table('music_team_recruits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('team_name', sa.String(length=100), nullable=False, comment='팀명'),
        sa.Column('church_name', sa.String(length=100), nullable=False, comment='교회명'),
        sa.Column('instruments_needed', sa.JSON(), nullable=False, comment='필요한 악기 목록'),
        sa.Column('team_type', sa.String(length=20), nullable=False, comment='팀 유형'),
        sa.Column('experience_required', sa.String(length=20), nullable=False, comment='요구 실력'),
        sa.Column('practice_location', sa.String(length=200), nullable=False, comment='연습 장소'),
        sa.Column('practice_schedule', sa.Text(), nullable=False, comment='연습 일정'),
        sa.Column('commitment', sa.String(length=100), nullable=True, comment='최소 활동 기간'),
        sa.Column('description', sa.Text(), nullable=False, comment='상세 설명'),
        sa.Column('requirements', sa.Text(), nullable=True, comment='지원 자격'),
        sa.Column('benefits', sa.Text(), nullable=True, comment='혜택'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='모집 마감일'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='모집 상태'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_team_recruits_id'), 'music_team_recruits', ['id'], unique=False)
    
    # Create music_team_applications table  
    op.create_table('music_team_applications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='제목'),
        sa.Column('desired_team_type', sa.String(length=20), nullable=False, comment='희망 팀 유형'),
        sa.Column('instruments', sa.JSON(), nullable=False, comment='연주 가능 악기'),
        sa.Column('experience_level', sa.String(length=20), nullable=False, comment='실력 수준'),
        sa.Column('experience_description', sa.Text(), nullable=True, comment='경력 설명'),
        sa.Column('desired_location', sa.String(length=100), nullable=False, comment='희망 활동 지역'),
        sa.Column('available_schedule', sa.Text(), nullable=False, comment='가능한 일정'),
        sa.Column('introduction', sa.Text(), nullable=False, comment='자기소개'),
        sa.Column('portfolio_links', sa.JSON(), nullable=True, comment='포트폴리오 링크'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('available_from', sa.DateTime(timezone=True), nullable=True, comment='활동 가능 시작일'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='상태'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_team_applications_id'), 'music_team_applications', ['id'], unique=False)
    
    # Create church_events table
    op.create_table('church_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False, comment='행사명'),
        sa.Column('church_name', sa.String(length=100), nullable=False, comment='주최 교회'),
        sa.Column('event_type', sa.String(length=20), nullable=False, comment='행사 유형'),
        sa.Column('description', sa.Text(), nullable=False, comment='행사 설명'),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False, comment='시작일시'),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False, comment='종료일시'),
        sa.Column('location', sa.String(length=200), nullable=False, comment='장소명'),
        sa.Column('address', sa.Text(), nullable=True, comment='상세 주소'),
        sa.Column('capacity', sa.Integer(), nullable=True, comment='최대 참가자 수'),
        sa.Column('current_participants', sa.Integer(), nullable=True, comment='현재 참가자 수'),
        sa.Column('fee', sa.Integer(), nullable=True, comment='참가비'),
        sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True, comment='등록 마감일'),
        sa.Column('contact_method', sa.String(length=20), nullable=False, comment='연락 방법'),
        sa.Column('contact_info', sa.String(length=100), nullable=False, comment='연락처'),
        sa.Column('requirements', sa.Text(), nullable=True, comment='참가 조건'),
        sa.Column('includes', sa.Text(), nullable=True, comment='포함 사항'),
        sa.Column('images', sa.JSON(), nullable=True, comment='행사 이미지 URL 배열'),
        sa.Column('status', sa.String(length=20), nullable=False, comment='행사 상태'),
        sa.Column('author_id', sa.Integer(), nullable=False, comment='작성자 ID'),
        sa.Column('church_id', sa.Integer(), nullable=True, comment='교회 ID (9998=커뮤니티)'),
        sa.Column('views', sa.Integer(), nullable=True, comment='조회수'),
        sa.Column('likes', sa.Integer(), nullable=True, comment='좋아요수'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_church_events_id'), 'church_events', ['id'], unique=False)

    # Set default values for new columns
    op.execute("UPDATE community_sharing SET status = 'available' WHERE status IS NULL")
    op.execute("UPDATE community_requests SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE job_posts SET status = 'open' WHERE status IS NULL")
    op.execute("UPDATE job_seekers SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE music_team_recruits SET status = 'open' WHERE status IS NULL")
    op.execute("UPDATE music_team_applications SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE church_events SET status = 'upcoming' WHERE status IS NULL")
    
    op.execute("UPDATE community_sharing SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE community_requests SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE job_posts SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE job_seekers SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE music_team_recruits SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE music_team_applications SET views = 0 WHERE views IS NULL")
    op.execute("UPDATE church_events SET views = 0 WHERE views IS NULL")
    
    op.execute("UPDATE community_sharing SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE community_requests SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE job_posts SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE job_seekers SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE music_team_recruits SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE music_team_applications SET likes = 0 WHERE likes IS NULL")
    op.execute("UPDATE church_events SET likes = 0 WHERE likes IS NULL")
    
    op.execute("UPDATE church_events SET current_participants = 0 WHERE current_participants IS NULL")
    op.execute("UPDATE church_events SET fee = 0 WHERE fee IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_church_events_id'), table_name='church_events')
    op.drop_table('church_events')
    op.drop_index(op.f('ix_music_team_applications_id'), table_name='music_team_applications')
    op.drop_table('music_team_applications')
    op.drop_index(op.f('ix_music_team_recruits_id'), table_name='music_team_recruits')
    op.drop_table('music_team_recruits')
    op.drop_index(op.f('ix_job_seekers_id'), table_name='job_seekers')
    op.drop_table('job_seekers')
    op.drop_index(op.f('ix_job_posts_id'), table_name='job_posts')
    op.drop_table('job_posts')
    op.drop_index(op.f('ix_community_requests_id'), table_name='community_requests')
    op.drop_table('community_requests')
    op.drop_index(op.f('ix_community_sharing_id'), table_name='community_sharing')
    op.drop_table('community_sharing')
    # ### end Alembic commands ###