"""Add AI agent and chat system tables

Revision ID: b4075dd9aed3
Revises: bb57c0ba2b2d
Create Date: 2025-08-10 02:57:47.566730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4075dd9aed3"
down_revision: Union[str, None] = "bb57c0ba2b2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "official_agent_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("detailed_description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_official_agent_templates_id"),
        "official_agent_templates",
        ["id"],
        unique=False,
    )
    op.create_table(
        "ai_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("church_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("detailed_description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=10), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("total_tokens_used", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["church_id"],
            ["churches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["official_agent_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_agents_id"), "ai_agents", ["id"], unique=False)
    op.create_table(
        "church_database_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("church_id", sa.Integer(), nullable=False),
        sa.Column("db_type", sa.String(length=50), nullable=True),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("database_name", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("connection_string", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tables_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["church_id"],
            ["churches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("church_id"),
    )
    op.create_index(
        op.f("ix_church_database_configs_id"),
        "church_database_configs",
        ["id"],
        unique=False,
    )
    op.create_table(
        "chat_histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("church_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("is_bookmarked", sa.Boolean(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["ai_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["church_id"],
            ["churches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_histories_id"), "chat_histories", ["id"], unique=False
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_history_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chat_history_id"],
            ["chat_histories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.add_column(
        "churches", sa.Column("subscription_plan", sa.String(length=50), nullable=True)
    )
    op.add_column("churches", sa.Column("gpt_api_key", sa.Text(), nullable=True))
    op.add_column(
        "churches", sa.Column("gpt_model", sa.String(length=50), nullable=True)
    )
    op.add_column("churches", sa.Column("max_tokens", sa.Integer(), nullable=True))
    op.add_column("churches", sa.Column("temperature", sa.Float(), nullable=True))
    op.add_column("churches", sa.Column("gpt_last_test", sa.DateTime(), nullable=True))
    op.add_column("churches", sa.Column("max_agents", sa.Integer(), nullable=True))
    op.add_column(
        "churches", sa.Column("monthly_token_limit", sa.Integer(), nullable=True)
    )
    op.add_column(
        "churches", sa.Column("current_month_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "churches", sa.Column("current_month_cost", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("churches", "current_month_cost")
    op.drop_column("churches", "current_month_tokens")
    op.drop_column("churches", "monthly_token_limit")
    op.drop_column("churches", "max_agents")
    op.drop_column("churches", "gpt_last_test")
    op.drop_column("churches", "temperature")
    op.drop_column("churches", "max_tokens")
    op.drop_column("churches", "gpt_model")
    op.drop_column("churches", "gpt_api_key")
    op.drop_column("churches", "subscription_plan")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_histories_id"), table_name="chat_histories")
    op.drop_table("chat_histories")
    op.drop_index(
        op.f("ix_church_database_configs_id"), table_name="church_database_configs"
    )
    op.drop_table("church_database_configs")
    op.drop_index(op.f("ix_ai_agents_id"), table_name="ai_agents")
    op.drop_table("ai_agents")
    op.drop_index(
        op.f("ix_official_agent_templates_id"), table_name="official_agent_templates"
    )
    op.drop_table("official_agent_templates")
    # ### end Alembic commands ###
